### ISSUE TITLE
Missing Sample Data Folder 

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#25]
with the AutoscoperM module- when launching Sample data- the cfg files are not found. 
Python terminal shows expected directory as .... C:/Users/username/AppData/Local/slicer.org/Slicer 5.3.0-2023-03-27/slicer.org/Extensions-31693/SlicerAutoscoperM/bin/sample_data/wrist.cfg

sample_data folder does not exist in the bin directory

**Comment by NicerNewerCar** [comment]
This is due to the `Autoscoper_INSTALL_SAMPLE_DATA` option being disabled
https://github.com/BrownBiomechanics/SlicerAutoscoperM/blob/444e2b87168d2da48ac5c4be0bf56c560683b6a6/SuperBuild/External_Autoscoper.cmake#L83

Moving forward I will be [registering sample data](https://github.com/Slicer/Slicer/blob/01984729eca68f0417ead58d87d3358912f094d4/Utilities/Templates/Modules/Scripted/TemplateKey.py#L66-L81) through Slicer itself.
