### ISSUE TITLE
OpenCL error at cfg open (Mayo) 

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#26]
Walked through the wrist data available on the gdrive with Cesar Lopez (Mayo Clinic), after correcting root paths - Autoscoper M crashed:

[FD] OpenCL error at D:\D\P\S-0-E-b\SlicerAutoscoperM-build\Autoscoper\libautoscoper\src\gpu\opencl\OpenCL.cpp:1000
[FD]   -59 CL_INVALID_OPERATION

**Comment by NicerNewerCar** [comment]
Looks like this is happening on an OpenCL 1.2 device when a buffer is getting [filled](https://github.com/BrownBiomechanics/Autoscoper/blob/60b3d6ec0a5e4b796ef97baaa7a3a9b0351280e7/libautoscoper/src/gpu/opencl/OpenCL.cpp#L996C32-L1000).

`CL_INVALD_OPERATION` is not one of the [standard error codes](https://registry.khronos.org/OpenCL/specs/2.2/html/OpenCL_API.html#clEnqueueFillBuffer) that `clEnqueueFillBuffer` returns.

[This person](https://github.com/KhronosGroup/OpenCL-Registry/issues/73) ran into the same issue with some Nvidia cards.

Could you please get the information about the video card they are using? (make, model, driver version, cuda version if applicable) 

Also which wrist data set did this happen on? (WN00105, WN00106, etc)

Thanks!

**Comment by amymmorton** [comment]
![Capture](https://user-images.githubusercontent.com/65619862/236298740-2f945005-5ef8-4e19-9588-beecc1614100.PNG)
![image002](https://user-images.githubusercontent.com/65619862/236298752-66c52a27-ce92-492b-82d8-9694dcb57a7e.png)

**Comment by NicerNewerCar** [comment]
It looks like the error is caused for the same reason as in [this issue](https://github.com/KhronosGroup/OpenCL-Registry/issues/73).

The `NVidia Quadro 600` is a [Fermi](https://www.techpowerup.com/gpu-specs/quadro-600.c1318) architecture card. 
The Fermi architecture only appears to support OpenCL `1.0.48` whereas Autoscopers minimum version is `1.2`

A quick review of the [OpenCL 1.0 r48 specs](https://registry.khronos.org/OpenCL/specs/opencl-1.0.pdf) confirms that there is no command `clEnqueueFillBuffer`

Since the GPU doesn't appear to be a viable option, it may be worthwhile looking into getting [OpenCL set up on the CPU](https://www.intel.com/content/www/us/en/developer/articles/tool/opencl-drivers.html)
